# Generated by Django 2.1.5 on 2019-02-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botsdetection',
            name='Hits',
        ),
        migrations.AddField(
            model_name='botsdetection',
            name='session_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='botsdetection',
            name='users',
            field=models.IntegerField(null=True),
        ),
    ]
